# Generated by Django 2.2.10 on 2021-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode_of_payment', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=200, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('paid_by', models.CharField(max_length=200, null=True)),
                ('received_by', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(null=True)),
                ('Tenure_date', models.DateTimeField(auto_now_add=True)),
                ('mode_of_payment', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_by', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
